
'''Snakefile for twoprime analysis'''

__author__ = 'Jay Hesselberth <jay.hesselberth@gmail.com>'

from datetime import date
today = date.today().isoformat()
workdir: 'results-twoprime/%s' % today

STRANDS = {'pos':'-strand +', 'neg':'-strand -'}
SIDES = {'5p':'-5', '3p':'-3'}
SCORES = ('A','B','C')

FASTA = config['FASTA'] 
BOWTIEIDX = config['BOWTIEIDX'] 
CHROMSIZE = config['CHROMSIZE']

from collections import namedtuple
sample_info = namedtuple('sample_info', ['description', 'url'])
SAMPLE_INFO = {id:sample_info(description, url) for id, description, url in 
               zip(config['samples'], config['descriptions'],
               config['urls'])}

rule all:
    input:
        expand('coverage/{sample}/{sample}.{side}.{strand}.bg.gz',
               sample=config['samples'], strand=STRANDS, side=SIDES),
        expand('coverage/{sample}/{sample}.{strand}.bw',
               sample=config['samples'], strand=STRANDS),
        expand('scores/{sample}/{sample}.{strand}.score{score}.bg.gz',
               sample=config['samples'], strand=STRANDS, score=SCORES),
        expand('scores/{sample}/{sample}.{strand}.score{score}.bw', 
               sample=config['samples'], strand=STRANDS, score=SCORES)

include: 'rules/fastq.snake'
include: 'rules/coverage.snake'
include: 'rules/genomedata.snake'
include: 'rules/scores.snake'
# include: 'rules/hub.snake'

